### ISSUE TITLE
I'm getting error while going to use this theme

### ISSUE THREAD

**Issue by bolaram** [creativecommons/wp-theme-base#17]
## Description
I'm getting error while going to use this theme
## Reproduction

1. Zip this repo
2. Upload this theme via WordPress dashboard panel
3. Activate the theme
4. See error.

## Expectation
Activate the theme and i can modify based on my preference.

## Screenshots
Fatal error: Class 'Queulat\Metabox' not found
Screenshot : https://prnt.sc/t8ikzv

## Environment

 - Device: Laptop
 - OS: Windows
 - Browser: Chrome

## Resolution

- [ ] I would be interested in resolving this bug.
- [x] I'd like to contribute on documentation of this theme

**Comment by hugosolar** [comment]
Yes, that error is because [Queulat](https://github.com/felipelavinz/queulat) is a mandatory dependency which has to be installed via [composer](https://getcomposer.org/). We're still working on this theme codebase and its documentation, so I would say it's still a work in progress.
I'm closing this issue
